/*
 * This source file was generated by the Gradle 'init' task
 */
package ec.com.uml;

public class Main {
  
    public static void main(String[] args) {
        
        Author author = new Author();
        author.setName("John Doe");
        Author author2 = new Author();
        author2.setName("Jane Doe");

        Book book1 = new BookPrinted("Java Basics", author, 300);
        Book book2 = new BookDigital("Advanced Java", author2, "PDF");

        Library library = new Library();
        library.addBook(book1);
        library.addBook(book2);

        library.showBooks();    

        User user = new User();
        user.setName("Alice");
        user.borrowBook(book1);
        user.borrowBook(book2);

        System.out.println("--- Book Information ---");
        library.showBooks();

    }
}
